name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

# on:

#   workflow_run:

#     workflows: ["Flutter CI"]

#     types:
#       - completed

# on:
#   push:
#     tags:
#       - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  GIT_CLIFF_VERSION: "2.10.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        # with:
        #   ref: ${{ github.ref_name }}
        #   fetch-depth: 0
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-git-cliff-${{ env.GIT_CLIFF_VERSION }}

      # - name: Install git-cliff
      #   run: |
      #     cargo install git-cliff

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-cliff-v2
      
      - name: Install git-cliff
        run: |
          if ! command -v git-cliff >/dev/null; then
            cargo install git-cliff
          fi
          
      - name: Generate CHANGELOG
        run: |
          git-cliff -o CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add CHANGELOG.md

          git commit -m "docs: update changelog [skip ci]" || true

          git push

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Pub Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/" --dart-define=BUILD_NUMBER=${{ github.run_number }}

      # - uses: softprops/action-gh-release@v2
      #   with:
      #     generate_release_notes: true
          # files: |
          #   build/web/**

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build

    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
  
      # - name: Send Email
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     secure: true

      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}

      #     subject: "✅ Flutter Web Deployment Success"

      #     to: your@email.com

      #     from: GitHub Actions

      #     body: |
      #       Deployment completed successfully.

      #       Repository:
      #       ${{ github.repository }}

      #       Branch:
      #       ${{ github.ref_name }}

      #       Commit:
      #       ${{ github.sha }}

      #       Workflow:
      #       ${{ github.workflow }}

      #       Run:
      #       https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            